drop schema public cascade;
drop table user if exists;
create table user (
  user_id integer primary key GENERATED BY DEFAULT AS IDENTITY,
  username varchar(32) not null,
  userpassword varchar(128) not null,
  email varchar(32) not null
);

drop table followerslist if exists;
create table followerslist (
  user_id integer,
  follower_id integer
);

drop table post if exists;
create table post (
  post_id integer primary key GENERATED BY DEFAULT AS IDENTITY,
  user_id integer not null,
  date_added timestamp,
  text varchar(150) not null
);